name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Date String
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - name: Archive Archolos Files
      uses: vimtor/action-zip@v1
      with:
        files: docs/assets/sources/archolos/
        dest: TheChroniclesOfMyrtana-All.zip
    - name: Archive Archolos GD3D11 Files
      uses: vimtor/action-zip@v1
      with:
        files: docs/assets/sources/archolos/system/GD3D11/
        dest: TheChroniclesOfMyrtana-GD3D11.zip
    - name: Upload Archolos Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./*.zip"
        allowUpdates: true
        artifactErrorsFailBuild: true
        removeArtifacts: true
        tag: ${{ env.date }}
        token: ${{ secrets.REPO_TOKEN }}
