name: Release
on:
  push:
    branches:
      - main
    paths:
      - '**'

jobs:
  build:
    if: startsWith(github.event.head_commit.message, 'build-zip:')
    runs-on: ubuntu-latest
    steps:
    - name: Install Checkout
      uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Run Pre-Build Tests
      run: python3 tests/pre_build.py
    - name: Build artifacts
      run: python3 release.py
    - name: Run Post-Build Tests
      run: python3 tests/post_build.py
    - name: Set Date String
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - name: Create Release with built artifacts
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./*.zip"
        allowUpdates: true
        artifactErrorsFailBuild: true
        removeArtifacts: true
        tag: ${{ env.date }}
        token: ${{ secrets.REPO_TOKEN }}
